---
- hosts: localhost
  become: true
  vars:
    pip_install_packages:
      - name: docker
  pre_tasks:
    - name: Install EPEL repo (CentOS only)
      package:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install python3 and python3-pip
      package:
        name: 
          - python3
          - python3-pip
        state: present
        update_cache: yes

  roles:
    - geerlingguy.docker



