---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: nginx
    docker_container:
      name: nginx
      image: nginx
      ports:
       - "80:80"
